### ISSUE TITLE
question

### ISSUE THREAD

**Issue by QuantumFox42** [KingWaffleIII/Nuker-Bot#1]
does the !play command role have the "Display role members separately from online members" turned on?

**Comment by KingWaffleIII** [comment]
Hello @QuantumFox42,
Fortunately, this is not the case. It has been deliberately turned off to keep the role inconspicuous, else what’s the point of having administrator permissions to be removed immediately? This role is also named “Member” to also remain discreet and before you ask, no, it does not conflict with existing roles named “Member”. 

**I feel I have answered this question to your liking so I am closing this issue now but if you need anymore information, don’t hesitate to ask :)**
