### ISSUE TITLE
dm

### ISSUE THREAD

**Issue by QuantumFox42** [KingWaffleIII/Nuker-Bot#4]
could you get the bot so it can dm everyone something right before the nuking??

**Comment by KingWaffleIII** [comment]
Hello @QuantumFox42,
Again, thank you for getting back to us! Once again, this is an odd request since direct messaging everyone in the server is an odd choice. If you don't mind, please elaborate on this feature and I will get back to you as quick as I can!

**Comment by QuantumFox42** [comment]
basically, I want to be able to input a message such as "lemons are cool, worship them" and right before it nukes it it will send everyone that

**Comment by KingWaffleIII** [comment]
Okay, I know understand the feature and its purpose. I will likely be developing this in the next development version so keep an eye out!
=> KingWaffleIII, project owner and administrator

**Comment by KingWaffleIII** [comment]
Hello,
this feature is being developed at the moment!

**Comment by KingWaffleIII** [comment]
Hello,
I am please to say that this feature has been completed and has been released in **v1.4**. Thank you!
